# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4d14a86a78b36a6ee9b5e85d476c216564716c71f086b4c1062de068ef925877a051cca9d3f07ca1f7b23a15d3f504a30b252ee40f85463a7a8ea89ca024782

test:
  secret_key_base: fbd1b4344d6c7669f10895acd2e42eecb8e9fdb472153435a4ca337273a1924ed9c200e228d5984ae30bab1ee3ba9ab61f150b83bcc6a613c124e2d78b5fd64e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
